/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockMaliciousTokenSol from "./MockMaliciousToken.sol";
export type { mockMaliciousTokenSol };
export type { MockERC20 } from "./MockERC20";
export type { MockNoDecimals } from "./MockNoDecimals";
export type { MockNonCompliantToken } from "./MockNonCompliantToken";
export type { MockRateOracle } from "./MockRateOracle";
export type { MockReentrantERC20 } from "./MockReentrantERC20";
export type { MockRevertingDecimals } from "./MockRevertingDecimals";
export type { MockUSDC } from "./MockUSDC";
