/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRateOracle,
  IRateOracleInterface,
} from "../../../contracts/StableOracleExchange.sol/IRateOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
    ],
    name: "getRate",
    outputs: [
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRateOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IRateOracleInterface {
    return new Interface(_abi) as IRateOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRateOracle {
    return new Contract(address, _abi, runner) as unknown as IRateOracle;
  }
}
