/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stableOracleExchangeSol from "./StableOracleExchange.sol";
export type { stableOracleExchangeSol };
import type * as mocks from "./mocks";
export type { mocks };
