/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRateOracle } from "./IRateOracle";
export type { StableOracleExchange } from "./StableOracleExchange";
